name: aliyundrive-checkin
on:
  schedule:
  - cron: 20 23 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Run checkin
        run: |
          python3 ./main.py
        env:
          REFRESH_TOKENS: ${{ secrets.REFRESH_TOKENS }}
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          DO_NOT_REWARD: 'true'
          PUSH_TYPES: 'SMTP'
          SMTP_HOST: 'smtp.office365.com'
          SMTP_PORT: '587'
          SMTP_TLS: 'true'
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_SENDER: ${{ secrets.SMTP_USER }}
          SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }}
          DD_TOKEN: ${{ secrets.dd_token }}
          DD_SECRET: ${{ secrets.dd_secret }}
      - uses: gautamkrishnar/keepalive-workflow@master
