name: Aliyun Signin

on:
  schedule:
   # 每天国际时间 17:20 运行一次, 中国时间 01:20
    - cron: '20 10 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ secrets.REFRESH_TOKENS }}
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          DO_NOT_REWARD: 'true'
          PUSH_TYPES: 'SMTP'
          SMTP_HOST: 'smtp.office365.com'
          SMTP_PORT: '465'
          SMTP_USER: 'eganegenie@outlook.com'
          SMTP_PASSWORD: '!q111111'
          SMTP_SENDER: 'egenegenie@outlook.com'
          SMTP_RECEIVER: 'chulonghui2013@163.com'
